# disable eureka by default
eureka:
  enabled: false
  registerWithEureka: false
  fetchRegistry: false

# Server configuration
server:
  context-path: /micro
  port: 8080

# use customers db
cloudant:
  db: customers
